### ISSUE TITLE
psbody?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [soubhiksanyal/RingNet#1]
can you tell me how to install psbody packages?

**Comment by ZHANG-SHI-CHANG** [comment]
i find it ...

**Comment by fox16789** [comment]
Do you know how to install psbody？

**Comment by huangfaan** [comment]
Could you tell me how to install psbody？

**Comment by TimoBolkart** [comment]
Please install the mesh processing library [MPI-IS/mesh](https://github.com/MPI-IS/mesh). You find all instruction on this page.
