### ISSUE TITLE
Differenciable FLAME decode model?

### ISSUE THREAD

**Issue by KangolHsu** [soubhiksanyal/RingNet#11]
In your paper ,you use Differenciable FLAME decode model to get 3d mesh by flame parameters, and  this FLAME decode model is fixed  during training .My question is How to get this  Differenciable FLAME decode model?

**Comment by soubhiksanyal** [comment]
We have our own implementation of the Flame model in tensorflow. For more information regarding this you can have a look at the following repository https://github.com/TimoBolkart/TF_FLAME. I hope that explains your query.
