### ISSUE TITLE
why the image in mesh folder is downward ?

### ISSUE THREAD

**Issue by Masquerades2015** [soubhiksanyal/RingNet#12]
hello, i run the demo.py ,  but the image ( generated obj file)  in mesh folder  is downward. how can i make it upward?

**Comment by soubhiksanyal** [comment]
I am not sure whether I get your question. In the obj file you get a 3D mesh. You can open this with any mesh viewing software (i.e. MeshLab) and make it upward.

**Comment by Masquerades2015** [comment]
> I am not sure whether I get your question. In the obj file you get a 3D mesh. You can open this with any mesh viewing software (i.e. MeshLab) and make it upward.

Thank you！I didn't know much about it before.
