### ISSUE TITLE
Having trouble with tensorflow/CUDA/absl

### ISSUE THREAD

**Issue by DrunkAI** [soubhiksanyal/RingNet#13]
I am new to programming and cv in general, so forgive me if my issues seem too simple.

I am using Ubuntu 18.04 and trying to replicate your included demo just to make sure the program is working.  I have repeatedly run into different problems that all seem to be related to CUDA and tensorflow.

I have heard that these programs are all very sensitive to driver versions and dependencies.  So far, the furthest I seem to get is to a point where I get an absl module missing error.  I am sure it is installed, and have tried various version.  At one point downgrading forced me to downgrade to tensorflow 1.12.  Still the same issue is popping up.  I am ready to start over step by step, as tedious as that is.  

I wonder if anybody could explain to me how to make sure that the versions of all the needed libraries and whatnot to run RingNet are correct.

**Comment by soubhiksanyal** [comment]
Can you post the error?
