### ISSUE TITLE
Will you provide code for building 2D feature loss?

### ISSUE THREAD

**Issue by zheLim** [soubhiksanyal/RingNet#14]
During the training, 2D feature loss is used. I am wondering if you can provide indexes of trajectories/candidate contour points? If you can provide the code of 2D feature loss, I'd most grateful.

**Comment by soubhiksanyal** [comment]
I will put the face indices of the trajectories of the contour points in later commit.

**Comment by zheLim** [comment]
@soubhiksanyal Thanks a lot, looking forward to your commit :)
