### ISSUE TITLE
Landmark detection

### ISSUE THREAD

**Issue by taylorlu** [soubhiksanyal/RingNet#16]
Hi, I would like to ask how to detect the 68 landmarks which PRNet/3DDFA does.
Thanks in advance.

**Comment by fastcode3d** [comment]
I have the same question. Have you solved your problem?

**Comment by soubhiksanyal** [comment]
One can potentially run openpose or some other landmark detector to get the 68 landmarks. For our project we used openpose detected landmarks

**Comment by fastcode3d** [comment]
Thank you for your reply, but actually I want to get the index corresponding to 68 landmarks in .obj. I found similar index in related projects of flame(https://github.com/TimoBolkart/TF_FLAME/blob/master/fit_3D_landmarks.py), but the vertex number of .obj is different from that of this project, so it can't be used. Is there any way to get it?

**Comment by soubhiksanyal** [comment]
I think you can use the https://github.com/soubhiksanyal/RingNet/blob/master/dynamic_contour_embedding.py function for loading the static and dynamic face indexes and their corresponding Barycentric coordinates. I have recently pushed this function to the repository. Let me know whether this was the thing you were looking for. Also check in this folder for the indices, https://github.com/soubhiksanyal/RingNet/tree/master/flame_model.

**Comment by fastcode3d** [comment]
Thank you very much. I'm studying this part of the code. I think that's what I'm looking for.

**Comment by shriyakak** [comment]
Hi @fastcode3d, I would like to ask did you get the indices for 68 landmarks in the .obj file generated by RingNet?
