### ISSUE TITLE
For pre-trained model

### ISSUE THREAD

**Issue by xinlinxie** [soubhiksanyal/RingNet#18]
hello,
thanks for your great works!
i want to follow your work, but i can't download the pretrained RingNet weights you provided on your project website. I've signed up, but the download is very slow and always broken,  Can you give me some advice?
thank you again!

**Comment by soubhiksanyal** [comment]
Are you still having the same problem?

**Comment by hzq-zjm** [comment]
> hello,
> thanks for your great works!
> i want to follow your work, but i can't download the pretrained RingNet weights you provided on your project website. I've signed up, but the download is very slow and always broken, Can you give me some advice?
> thank you again!

Hello, I have the same problem as you. Did you download it successfully? Can you send me a copy? My email is 15620730094@163.com.  Thanks very much.

**Comment by hzq-zjm** [comment]
> hello,
> thanks for your great works!
> i want to follow your work, but i can't download the pretrained RingNet weights you provided on your project website. I've signed up, but the download is very slow and always broken, Can you give me some advice?
> thank you again!

@xinlinxie   Hello, I have the same problem as you. Did you download it successfully? Can you send me a copy? My email is 15620730094@163.com. Thanks very much.

**Comment by liyuanyaun** [comment]
@xinlinxie @hzq-zjm hi two guys, do you download it successfully?Can you send me a copy? My email is liyuanyuanmath@163.com. Thanks very much.

**Comment by JohnFive5** [comment]
@xinlinxie @hzq-zjm @liyuanyaun @cssddnnc9527 Excuse me,could you please send me a copy?My email is 13534997217@163.com. Thanks a lot!
