### ISSUE TITLE
Output mesh render is blank

### ISSUE THREAD

**Issue by Addarsh** [soubhiksanyal/RingNet#19]
Hi,

I'm running the following command with the downloaded pre-trained model:
python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output

and I'm seeing the following output file.
![output](https://user-images.githubusercontent.com/13083390/66017889-85f00000-e491-11e9-8966-d8b5c4243e33.png)

The renders are all dark. When I ran the same command with the flag --save_obj_file=True,
the obj file was successfully created and I could view it successfully in Blender.
<img width="1094" alt="blender-mesh" src="https://user-images.githubusercontent.com/13083390/66018040-437af300-e492-11e9-9bfb-931f07b3bc30.png">

**Comment by soubhiksanyal** [comment]
I think the problem is occurring due to opendr version. Can you share your opendr version? Use 0.77

**Comment by RobinROAR** [comment]
> I think the problem is occurring due to opendr version. Can you share your opendr version? Use 0.77

My opendr version is 0.77, however, I meet the same issue. The output image is blank but the obj is corrent.

**Comment by digbose92** [comment]
@Addarsh and @RobinROAR have you been able to solve this problem ? I am facing the same issue

**Comment by RobinROAR** [comment]
> @Addarsh and @RobinROAR have you been able to solve this problem ? I am facing the same issue

Not yet. Feels bad

**Comment by mlyarthur** [comment]
i have the same problem as yours.How do you visualize the .obj file ?   is  the blender a software?

**Comment by mlyarthur** [comment]
@Addarsh  i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?

**Comment by RobinROAR** [comment]
> @Addarsh i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?

You can try meshlab

**Comment by soubhiksanyal** [comment]
I have updated the requirements. Can you please reinstall the updated requirements? I think that should work. My opendr version is still 0.77 and that is only compatible with python 2.7. Can you please check your python version in the virtualenv too?

**Comment by bradison18** [comment]
> I have updated the requirements. Can you please reinstall the updated requirements? I think that should work. My opendr version is still 0.77 and that is only compatible with python 2.7. Can you please check your python version in the virtualenv too?

But mesh libraries work only with Pythhon 3.5 + and without installing mesh it is giving a error that "psbody-mesh is not available pls install it".

**Comment by KeyKy** [comment]
> I have updated the requirements. Can you please reinstall the updated requirements? I think that should work. My opendr version is still 0.77 and that is only compatible with python 2.7. Can you please check your python version in the virtualenv too?

I work in python2.7 and meet the same problem.

**Comment by TimoBolkart** [comment]
> > I have updated the requirements. Can you please reinstall the updated requirements? I think that should work. My opendr version is still 0.77 and that is only compatible with python 2.7. Can you please check your python version in the virtualenv too?
> 
> But mesh libraries work only with Pythhon 3.5 + and without installing mesh it is giving a error that "psbody-mesh is not available pls install it".I even tried installing in 2.7 from the alternate link that you have provided but it is not getting installed.

What error do you get when using Python 2.7 if installing the forked [mesh repo](https://github.com/TimoBolkart/mesh)?

**Comment by bradison18** [comment]
> > @Addarsh i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?
> 
> You can try meshlab

I am able to get the 3D face but not that neutral expression can u pls help me in that issue.

**Comment by soubhiksanyal** [comment]
> > > @Addarsh i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?
> > 
> > 
> > You can try meshlab
> 
> I am able to get the 3D face but not that neutral expression can u pls help me in that issue.

python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output --save_obj_file=True --save_flame_parameters=True --neutralize_expression=True
You need to set the flag  neutralize_expression true

**Comment by bradison18** [comment]
> > > > @Addarsh i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?
> > > 
> > > 
> > > You can try meshlab
> > 
> > 
> > I am able to get the 3D face but not that neutral expression can u pls help me in that issue.
> 
> python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output --save_obj_file=True --save_flame_parameters=True --neutralize_expression=True
> You need to set the flag neutralize_expression true



> > > > @Addarsh i have the same problem as yours.How do you visualize the .obj file ? is the blender a software?
> > > 
> > > 
> > > You can try meshlab
> > 
> > 
> > I am able to get the 3D face but not that neutral expression can u pls help me in that issue.
> 
> python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output --save_obj_file=True --save_flame_parameters=True --neutralize_expression=True
> You need to set the flag neutralize_expression true

yes I have run the same command with neutralize_expression True.I ended up getting the error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
At line 80 of serialization.py "**dd = pickle.load(open(fname_or_dict))**"

**Comment by bradison18** [comment]
> > > I have updated the requirements. Can you please reinstall the updated requirements? I think that should work. My opendr version is still 0.77 and that is only compatible with python 2.7. Can you please check your python version in the virtualenv too?
> > 
> > 
> > But mesh libraries work only with Pythhon 3.5 + and without installing mesh it is giving a error that "psbody-mesh is not available pls install it".I even tried installing in 2.7 from the alternate link that you have provided but it is not getting installed.
> 
> What error do you get when using Python 2.7 if installing the forked [mesh repo](https://github.com/TimoBolkart/mesh)?

when I run the make command I got this error :
Given no hashes to check 137 links for project 'pip': discarding no candidates
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1
Can u please help me in this issue.

**Comment by soubhiksanyal** [comment]
> tting the error
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> At line 80 of serialization.py "**dd = pickle.load(open(fname_or_dict))**" . I am working in Python 3.6 and got the mesh and flame parameters properly but I am not able to get this neut


I think this error is caused caused by a mismatch of pickle for python 2.7 and python 3.6. Can you try pickle.load(*, encoding='latin1')

Source: https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

**Comment by bradison18** [comment]
> > tting the error
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> > At line 80 of serialization.py "**dd = pickle.load(open(fname_or_dict))**" . I am working in Python 3.6 and got the mesh and flame parameters properly but I am not able to get this neut
> 
> I think this error is caused caused by a mismatch of pickle for python 2.7 and python 3.6. Can you try pickle.load(*, encoding='latin1')
> 
> Source: https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

No, it again gave the same error(UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte). I even tried encoding = 'bytes' it also didn't work.

**Comment by bradison18** [comment]
> > tting the error
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> > At line 80 of serialization.py "**dd = pickle.load(open(fname_or_dict))**" . I am working in Python 3.6 and got the mesh and flame parameters properly but I am not able to get this neut
> 
> I think this error is caused caused by a mismatch of pickle for python 2.7 and python 3.6. Can you try pickle.load(*, encoding='latin1')
> 
> Source: https://stackoverflow.com/questions/28218466/unpickling-a-python-2-object-with-python-3

It worked thaks a lot for replying back the link that u gave stated that pickle.load(open('flame.pkl','rb'),embeddings='latin1') is the replacement in python3 . Once again thaks for replying
