### ISSUE TITLE
How to get the supplementary materials

### ISSUE THREAD

**Issue by xtsdylyx** [soubhiksanyal/RingNet#2]
I can't find the supplementary materials of this CVPR2019 paper in project website. 
When to release it?
Thanks!

**Comment by soubhiksanyal** [comment]
We are right now working on the supplementary video for some modifications. The plan is to release it within few days. I will update it in the project page and here as soon as it is done.

**Comment by TimoBolkart** [comment]
You find the supplementary video here: https://youtu.be/6wPQaJBgreE
