### ISSUE TITLE
expression problem

### ISSUE THREAD

**Issue by skygoo** [soubhiksanyal/RingNet#24]
Could the FLAME model fit the expression around the eyes? According to my test, I feel that the expression fit has some problem when close the eyes. Is there something wrong with my operation? 
![close1](https://user-images.githubusercontent.com/28951060/69852514-69b8e580-12bf-11ea-9ca1-c6d7e3bcf3eb.png)

**Comment by soubhiksanyal** [comment]
No with this regression model it is difficult to get close eyes. The network was not particularly trained on closed eye images, which can cause this. But original FLAME model with extra expression components can close eyes.
