### ISSUE TITLE
How to project 3D points to 2D image using predicted camera parameter?

### ISSUE THREAD

**Issue by maweibest** [soubhiksanyal/RingNet#28]
I am wondering, during training, the 2D feature loss requires to project 3D feature points onto 2D plain. How is it done using the 1x3 vector of the predicted camera parameter? Any training code for the project? This is also important if one wants to align the output 3D mesh with the input 2D image.

**Comment by qianxinchun** [comment]
Have you solved your problem?

**Comment by soubhiksanyal** [comment]
It is an orthographic projection. Ideally one can use the following code to project the 3D landmarks to 2D

https://github.com/akanazawa/hmr/blob/master/src/tf_smpl/projection.py

Please be careful on which you consider as scale and what you consider as translation.
