### ISSUE TITLE
ImportError: No module named psbody.mesh

### ISSUE THREAD

**Issue by JaredS215** [soubhiksanyal/RingNet#31]
I followed the instructions for cloning and building [mesh](https://github.com/MPI-IS/mesh) but when I run demo I get:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/username/RingNet/demo.py", line 45, in <module>
    from psbody.mesh import Mesh
ImportError: No module named psbody.mesh`

How do I tell the RingNet virtual environment to load mesh?  I tried running setup install on mesh in the RingNet virtual environment and just got more errors.  mesh appears to be python 3 now and RingNet is Python 2 so do I have to use an older version of mesh that is python 2?

**Comment by soubhiksanyal** [comment]
I have updated all the requirements and provided a fork for the mesh package which can work with pyhthon 2.7. You can check the update README. I think that should solve the problem.
