### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by bradison18** [soubhiksanyal/RingNet#33]
python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output --save_obj_file=True --save_flame_parameters=True --neutralize_expression=True
when I run this command its not giving the output of neutral_expression , I have copied the flame models to the flame_model folder. It has given at line 80 in serialization.py "**dd = pickle.load(open(fname_or_dict))**"
Pls help me in solving this issue and I am using pyton 3.6 as mesh libraries are working only in python 3.5+

**Comment by arintharoza** [comment]
Hi @bradison18! I am facing the same problem. How did you manage to solve this?
