### ISSUE TITLE
Output mesh render is blank and the pose of the mesh is wrong 

### ISSUE THREAD

**Issue by Qingqingniu** [soubhiksanyal/RingNet#34]
Hi,

When I run the following command with the downloaded pre-trained model:
python -m demo --img_path ./input_images/000001.jpg --out_folder ./RingNet_output --save_obj_file=True

and I'm seeing the following output file.
output
![000001](https://user-images.githubusercontent.com/38486462/79104342-f791fa80-7da0-11ea-8eb4-252755155331.png)
The pose of the reconstructed mesh is like this :
![00001-obj](https://user-images.githubusercontent.com/38486462/79104507-5192c000-7da1-11ea-89bc-ddfdc88ea41b.png)
My opendr version is 0.77

**Comment by flynnamy** [comment]
Hi Qingqingniu, I meet same problem.Have you solved it?@Qingqingniu

**Comment by Qingqingniu** [comment]
No,I haven`t solved it,but I thing the main reason is  that 'v' is not definded

**Comment by Qingqingniu** [comment]
> Hi Qingqingniu, I meet same problem.Have you solved it?@Qingqingniu
No,I haven`t solved it,but I thing the main reason is that 'v' is not definded

**Comment by Qingqingniu** [comment]
@flynnamy No,I haven`t solved it,but I thing the main reason is that 'v' is not definded

**Comment by hbinol** [comment]
@Qingqingniu, I am having exactly this issue. Have you solved it?
I wonder this is a renderer or matplotlib issue.

**Comment by srxdev0619** [comment]
Hi folks, I too get a mesh that is upside-down, like in the figure posted by @Qingqingniu. Is there any fix for this?

**Comment by bruinxiong** [comment]
@Qingqingniu @srxdev0619 same issue, is there any fix for this ?

**Comment by ty625911724** [comment]
I use the pose parameters with other render, get the same up-sides results. Is there any fix for this?
