### ISSUE TITLE
Can't fit closed eyes

### ISSUE THREAD

**Issue by wx176** [soubhiksanyal/RingNet#35]
@soubhiksanyal  I tested RingNet with some images extracted from RAVDESS. It seems RingNet can't work well for closed eyes, just as the following image shows.
![027](https://user-images.githubusercontent.com/8123192/79200744-7eaaa580-7e69-11ea-8914-740e8a154165.png)
Is this because you just used 50 expression blendshapes, or because the limitation of the training data, or others?

**Comment by soubhiksanyal** [comment]
True, this is one limitation. But this limitation mostly comes from the training data. I do not think we have used images with closed eyes for training. But potentially FLAME plus RingNet can be used for closing eyes if proper training data is used.

**Comment by wx176** [comment]
Got it! Thanks!
