### ISSUE TITLE
Requirements reference Python3-only library

### ISSUE THREAD

**Issue by geeschmidt** [soubhiksanyal/RingNet#38]
This project requires pyrender which requires unversioned imageio, which no longer supports Python 2.7 since February.

**Comment by soubhiksanyal** [comment]
Pyrender is only required if you only want to visualise the dynamic contour loading. You can use any other replacements for pyrender or comment that part of the code.

**Comment by geeschmidt** [comment]
No problem, just wanted to make you aware of the broken dependency.
