### ISSUE TITLE
basic information about output of voca model

### ISSUE THREAD

**Issue by Adorablepet** [soubhiksanyal/RingNet#46]
run the following command:
``` bash
python -m demo --img_path ./input_images/000013.jpg --out_folder ./RingNet_output --save_obj_file=True --save_flame_parameters=True --neutralize_expression=True
```
If I input a face image and generate the input of voca through the above command, is there any way to save the 3d information of the input image and rewrite it into the output obj file of voca, yes, the output of voca  Is there any texture information about the input image? That is to say, the output of voca is an obj file with 3d model information (can contain v, f, vn, vf, etc.), mtl file, texture png. Thanks.

**Comment by TimoBolkart** [comment]
Can you please describe your use case. VOCA uses a template mesh in FLAME mesh topology along with an audio file and generates a speech-driven animation.

**Comment by Adorablepet** [comment]
You have updated my question on the `voca` project, thanks.
