### ISSUE TITLE
How to add texture for the 3D model?

### ISSUE THREAD

**Issue by 12345data** [soubhiksanyal/RingNet#47]
When I tried this repository many of the meshes looks similar with another. Hence the texture is really important for identification. How can I add texture to the meshes for using them in VOCA. I have tried with TF_FLAME for creating texture for the mesh using the image file but it was not usable in VOCA. Can you suggest how can I do this?

**Comment by wqs111000** [comment]
Same issue

**Comment by TimoBolkart** [comment]
We added a demo to output a textured mesh (i.e. run with flag --save_texture=True). We also revised the texture handling for VOCA, such that it directly works with the TF_FLAME output. I either of these two options helps you
