### ISSUE TITLE
Quantitative Evaluation 

### ISSUE THREAD

**Issue by HOMGH** [soubhiksanyal/RingNet#52]
@soubhiksanyal  Hi Soubhik, Thanks for your great work. The quantitative evaluation of your model is a little bit vague.  Based on what you reported, you computed the error using the method in [this paper](https://arxiv.org/abs/1803.05536), which
computes the distance from ground truth scan points to the estimated mesh surface. I went through that paper but computing the scan-to-mesh distance between the predicted meshes and the
scans is still unclear to me. Would you please share the code you used for the evaluation?
Appreciate your time.

**Comment by xianzhongma** [comment]
I have the same problem.

**Comment by soubhiksanyal** [comment]
We have released the evaluation code for NoW validation set. You can have an idea about the metric from the code base 

https://github.com/soubhiksanyal/now_evaluation
