### ISSUE TITLE
Landmark correspondences

### ISSUE THREAD

**Issue by t-martyniuk** [soubhiksanyal/RingNet#56]
In the paper (section 3.4) you state the following:

_Given the FLAME template mesh, we define for each OpenPose [29] keypoint the corresponding 3D point in the mesh surface. Note that this is the only place where we provide supervision that connects 2D and 3D. This is done only once. While the mouth, nose, eye, and eyebrow key- points have a fixed corresponding 3D point (referred to as static 3D landmarks), the position of the contour features changes with head pose (referred to as dynamic 3D land- marks)_

How do you choose the corresponding 3D points out of 5k+ FLAME mesh vertices? Can you provide those correspondences (OpenPose facial landmarks in 2D <-> vertices of FLAME model in 3D)?

**Comment by soubhiksanyal** [comment]
We have already provided the correspondence here:  https://github.com/soubhiksanyal/RingNet/tree/master/flame_modelhttps://github.com/soubhiksanyal/RingNet/tree/master/flame_model
You can find them in the embeddings file
