### ISSUE TITLE
No FLAME_texture_data.npy?

### ISSUE THREAD

**Issue by wbensvage** [soubhiksanyal/RingNet#58]
It seems the link to download FLAME_texture_data.npy is broken? Is there any other way to download that>

**Comment by TimoBolkart** [comment]
Please check again, the link [FLAME_texture_data](http://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_texture_data.zip) provided in the readme works, maybe there was some problem with the server when you tried it.

**Comment by wbensvage** [comment]
> Please check again, the link [FLAME_texture_data](http://files.is.tue.mpg.de/tbolkart/FLAME/FLAME_texture_data.zip) provided in the readme works, maybe there was some problem with the server when you tried it.

Great! Thank you!

**Comment by CarminaP** [comment]
If you are still having trouble, be sure to be logged in the [FLAME website](https://flame.is.tue.mpg.de/index.html) first.
