### ISSUE TITLE
Mismatch of  RingNet output and FLAME parameter

### ISSUE THREAD

**Issue by zheLim** [soubhiksanyal/RingNet#7]
Greetings.
RingNet output a 159-dimensional vector. which contains 100-dimensional shape parameters, 50-dimension expression parameter and 6-dimensional pose parameter.
However, in Flame, the shape parameter is in shape (300,), expression parameter is in shape (100,), pose parameter is in shape (12,)

https://github.com/Rubikplayer/flame-fitting/blob/d3c4d3d4284d9ba8d36be0b224de7ce133301ebc/hello_world.py#L25-L27

If you can give some explanation, I'd be most grateful.
Thanks in advance!

**Comment by TimoBolkart** [comment]
RingNet outputs a subset of the FLAME parameters. These parameters are the first 100 shape parameters, first 50 expression parameters, and the pose parameters for the global rotation (FLAME pose parameters 1-3) and the jaw rotation (FLAME pose parameters 7-9). Does this answer your question?

**Comment by zheLim** [comment]
> RingNet outputs a subset of the FLAME parameters. These parameters are the first 100 shape parameters, first 50 expression parameters, and the pose parameters for the global rotation (FLAME pose parameters 1-3) and the jaw rotation (FLAME pose parameters 7-9). Does this answer your question?

Thanks for your kindly reply :)
Still I am curious on two points. 1. In order to use RingNet output on FLAME, the rest paramters should be padded with zeros? 2. Why RingNet output subset instead of full set of parameters?
Looking forward for your reply.

**Comment by TimoBolkart** [comment]
Yes, you just set the remaining parameters to zero. First, 100 shape and 50 expression parameters are sufficient to explain most of the data variation. Second, we minimize a landmark loss when training RingNet, and these landmarks only provide sparse supervision. Using fewer parameters makes it then easier to train.

**Comment by zheLim** [comment]
I see.
Just wondering if this few parameters is enough for RingNet, why FLAME should use that many parameters?

**Comment by TimoBolkart** [comment]
FLAME is previously also used to register high-resolution scans. Explaining detailed 3D scans provide you the information you need to optimize for all parameters. Landmarks only sparsely sample the face and a significant amount of information about the face shape is lost when using landmarks only. Hence more parameters will not provide you better shape results. The sparse supervision provided by the landmarks is the main limiting factor, not the number of FLAME parameters.

**Comment by zheLim** [comment]
> FLAME is previously also used to register high-resolution scans. Explaining detailed 3D scans provide you the information you need to optimize for all parameters. Landmarks only sparsely sample the face and a significant amount of information about the face shape is lost when using landmarks only. Hence more parameters will not provide you better shape results. The sparse supervision provided by the landmarks is the main limiting factor, not the number of FLAME parameters.

Thanks a lot!

**Comment by uniBruce** [comment]
Hi, thanks for the great work. I am wondering if there is a way to add the expression parameters into the visualize function in demo.py. I want to observe the coherence of an expression sequence showed in Flame model, but I don't know how to obtain the 2D projection of Flame model, could you do me a favor on this?
