### ISSUE TITLE
2D Projection

### ISSUE THREAD

**Issue by uniBruce** [soubhiksanyal/RingNet#8]
Hi, thanks for the amazing work. I have been doing some research work on expressions, and I decided to use RingNet to extract the expression parameters. However, I don't know how to use these parameters to realize 3D visualization. In addition, to observe the coherence of the expression sequence, I need to obtain the 2D projection of Flame model. Could you do me a favor on these problems?

**Comment by soubhiksanyal** [comment]
I am not sure whether I understand your question correctly. The last 50 parameters of the RingNet output corresponds to the expression of the FLAME model. One can take these parameters and use it with https://github.com/TimoBolkart/TF_FLAME or https://github.com/Rubikplayer/flame-fitting to realize the 3D visualization of expressions on faces. You can also check the example provided in the script https://github.com/soubhiksanyal/RingNet/blob/master/util/using_flame_parameters.py, which neutralize the expressions to generate a FLAME template.
